name: kakiso_reseller_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1
  google_sign_in: ^6.0.0
  iconsax: ^0.0.8
  iconsax_flutter: ^1.0.1
  lottie: ^3.1.0   # or latest
  get: ^4.6.5
  get_storage: ^2.1.1
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.10
  flutter_native_contact_picker: ^0.0.11
  intl: ^0.20.2
  http: ^1.5.0
  graphql_flutter: ^5.2.1
  flutter_secure_storage: ^9.2.4

  # --- NEW PACKAGES FOR DOWNLOAD & SHARE ---
  path_provider: ^2.1.2   # To access file system
  share_plus: ^10.0.0     # To share text and files
  gal: ^2.3.0             # To save images to Gallery
  pdf: ^3.10.4
  printing: ^5.11.0
  video_player: ^2.9.1 
  dio: ^5.0.0
  razorpay_flutter: ^1.4.0 
  # -----------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/videos/
    - assets/images/posters/
    - assets/images/icons/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/products/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

flutter_launcher_icons: 
  android: "launcher_icon"
  ios: true 
  image_path: "assets/logos/k_logo.png"
  min_sdk_android: 21