import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:kakiso_reseller_app/models/product.dart';

class PdfService {
  /// Generates a PDF catalog with custom Business Name and Reselling Prices
  static Future<void> createAndShareCatalog({
    required String categoryName,
    required List<ProductModel> products,
    required String businessName,
    required double extraMargin,
  }) async {
    final pdf = pw.Document();

    // 1. Pre-fetch images using 'networkImage' from the printing package.
    // This fixes the "Unable to guess image type" error by handling WebP/formats automatically.
    final itemsToPrint = products.take(20).toList();
    final List<pw.ImageProvider?> productImages = [];

    for (var product in itemsToPrint) {
      try {
        // networkImage downloads and decodes the image using Flutter's engine
        final provider = await networkImage(product.image);
        productImages.add(provider);
      } catch (e) {
        // If image fails to load, add null placeholder
        productImages.add(null);
      }
    }

    // 2. Build PDF Page(s)
    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(20),
        header: (context) => _buildHeader(categoryName, businessName),
        build: (context) {
          return [
            pw.GridView(
              crossAxisCount: 2,
              childAspectRatio: 0.65,
              crossAxisSpacing: 10,
              mainAxisSpacing: 10,
              children: List.generate(itemsToPrint.length, (index) {
                final product = itemsToPrint[index];
                final imageProvider = productImages[index];

                // CALCULATE NEW PRICE
                double basePrice = double.tryParse(product.price) ?? 0;
                double finalPrice = basePrice + extraMargin;

                return pw.Container(
                  padding: const pw.EdgeInsets.all(8),
                  decoration: pw.BoxDecoration(
                    border: pw.Border.all(color: PdfColors.grey300),
                    borderRadius: pw.BorderRadius.circular(8),
                  ),
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      // Image Section
                      pw.Expanded(
                        child: imageProvider != null
                            ? pw.Center(
                                child: pw.Image(
                                  imageProvider, // Use the provider directly
                                  fit: pw.BoxFit.contain,
                                ),
                              )
                            : pw.Center(
                                child: pw.Text(
                                  "No Image",
                                  style: const pw.TextStyle(
                                    color: PdfColors.grey,
                                  ),
                                ),
                              ),
                      ),
                      pw.SizedBox(height: 8),

                      // Title
                      pw.Text(
                        product.name,
                        maxLines: 2,
                        style: pw.TextStyle(
                          fontSize: 10,
                          fontWeight: pw.FontWeight.bold,
                        ),
                      ),
                      pw.SizedBox(height: 4),

                      // RESELLER PRICE (Calculated)
                      pw.Text(
                        "Price: Rs.${finalPrice.toStringAsFixed(0)}",
                        style: pw.TextStyle(
                          fontSize: 12,
                          fontWeight: pw.FontWeight.bold,
                          color: PdfColors.purple,
                        ),
                      ),
                    ],
                  ),
                );
              }),
            ),
            pw.SizedBox(height: 20),
            pw.Center(
              child: pw.Text(
                "Catalog generated by $businessName",
                style: const pw.TextStyle(
                  color: PdfColors.grey500,
                  fontSize: 10,
                ),
              ),
            ),
          ];
        },
      ),
    );

    // 3. Share PDF
    await Printing.sharePdf(
      bytes: await pdf.save(),
      filename: '${businessName}_${categoryName}_Catalog.pdf',
    );
  }

  static pw.Widget _buildHeader(String title, String shopName) {
    return pw.Column(
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              title.toUpperCase(),
              style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
            ),
            // Custom Shop Name
            pw.Text(
              shopName,
              style: const pw.TextStyle(fontSize: 14, color: PdfColors.purple),
            ),
          ],
        ),
        pw.Divider(),
        pw.SizedBox(height: 10),
      ],
    );
  }
}
